export const nav:string;
export const links:string;
export const trans:string;
export const close:string;
export const toggleWrapper:string;
export const toggle:string;
export const link:string;
export const active:string;
export const modal:string;
